## To modify by developper(s) of the plugin

[plugin-info]
SHORT_PLUGIN_NAME = 'daqmx'  #for instance daqmx
package-url = 'https://github.com/CEMES-CNRS/pymodaq_plugins_daqmx' #to modify
description = 'Hardware plugins for PyMoDAQ using the NiDAQmx framework (pydaqmx wrapper)'

author = 'SÃ©bastien Weber'
author-email = 'sebastien.weber@cemes.fr'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = ['pydaqmx']
##